# Generated by Django 6.1.1 on 2026-09-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('carrinho', 'No Carrinho'), ('pendente', 'Pagamento Pendente'), ('caminho', 'A caminho'), ('entregue', 'Produto Entregue')], default='carrinho', max_length=30)),
            ],
        ),
    ]
