# Generated by Django 6.1.1 on 2026-09-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('desconto', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('validade', models.DateField()),
                ('utilizado', models.BooleanField(default=False)),
            ],
        ),
    ]
